### ISSUE TITLE
Unable to make project in Archlinux VM

### ISSUE THREAD

**Issue by primitiveType** [kiibohd/controller#109]
Trying to get set up to build my own custom layouts, and ran into an issue that I can't find a way around. I am seeing exactly the same problem that was in this closed issue : https://github.com/kiibohd/controller/issues/13  
I downloaded the arch linux VM, logged in, did a git pull, then followed the exact instructions here:
https://github.com/kiibohd/controller/wiki/Building

```
$ mkdir build
$ cd build
$ cmake ..
$ make
```
the output is exactly the same as in the link posted above, but I'll screen cap it here as proof. I also tried changing the chip in CMakeLists.txt (and cleaned the build directory) but it made no difference.

![image](https://cloud.githubusercontent.com/assets/1714450/15060984/1257a03e-12fe-11e6-9090-e287fad1e5a5.png)

**Comment by haata** [comment]
It looks like the kll directory might be stale.

cd kll
git pull

then try again.

**Comment by primitiveType** [comment]
Thanks, I think that did it. I also had to clean the build directory and redo the cmake.
