### ISSUE TITLE
Matrix.h - Defining rows and columns?

### ISSUE THREAD

**Issue by mwood-uk** [kiibohd/controller#162]
Sorry if this is not the correct place to be asking (i'm new to well everything here)

I think i'm having problems defining the rows and columns in Matrix.h (i'm using a teensy 3.2)
I'm using pin 0-11 for columns and pins 15-19 for rows.

Is this correct?
_// Define Rows (Sense) and Columns (Strobes)
GPIO_Pin Matrix_cols[] = { PTB16(B,16), PTB17(B,17), PTD0(D,0), PTA12(A,12), PTA13(A,13), PTD7(D,7), PTD4(D,4), PTD2(D,2), PTD3(D,3), PTC3(C,3), PTC4(C,4), PTC6(C,6) };
GPIO_Pin Matrix_rows[] = { PTC0(C,0), PTB0(B,0), PTB1(B,1), PTB3(B,3), PTB2(B,2) };_

Could i also confirm that im flashing the teensy with the hex file located in: controller/Keyboards/ *ing.gcc

**Comment by haata** [comment]
Yes, that looks correct.
Please re-open if you still need help.
