### ISSUE TITLE
Build error: make[2]: execvp: ../kll/kll.py: Permission denied

### ISSUE THREAD

**Issue by wilecoyote2015** [kiibohd/controller#184]
Hello all,
I have followed the steps described in the build and installation guide to set up my system (Arch Linux, 64Bit). Using any .bash script as well as manual build with cmake fails with terminal output:

`[  4%] Generating KLL Layout
make[2]: execvp: ../kll/kll.py: permission denied
make[2]: *** [CMakeFiles/kiibohd.elf.dir/build.make:68: generatedKeymap.h] Error 127
make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/kiibohd.elf.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by haata** [comment]
It looks like you cloned or ran the build as root.

You may need to start with a fresh git clone.

**Comment by wilecoyote2015** [comment]
Ah, thank you!
Solved it this way, so the issue can be closed.
