### ISSUE TITLE
macOS-specific functions

### ISSUE THREAD

**Issue by pointlessone** [kiibohd/controller#192]
Hi,
I'd like to map macOS-specific function such as Mission Control and Dashboard. I assume those are somewhere in Consumer Control Codes but I can not find anything relevant. Are they documented? Does Apple use custom CONS values?

**Comment by JBonifacio** [comment]
I looked through the overleaf document and didn't see these either... you might want to use macros instead.

_TRIGGER_ : U["LCTRL","RCTRL"] + U"UP"

**Comment by jceaser** [comment]
these actions are not listed in the Consumer control codes, I think you do a macro.

**Comment by haata** [comment]
I'm not aware of any USB HID specific codes for macOS functions (though I really want to be able to send the Fn key in a generic way...).

If someone is aware of a standard/non-standard USB code for macOS function keys, let me know. :D
