### ISSUE TITLE
Default Aria Files Leaves Certain Keys Not Working and Switched

### ISSUE THREAD

**Issue by TWDickson** [kiibohd/controller#209]
Forgive me but I am a bit new to this, I've been attempting to build custom firmware so I can finally mod in shift + esc to ` but unfortunately I can't get the vanilla firmware working

Steps:
1. Cloned the controller git
2. Started the docker vm
3. Launched the docker VM
4. Modified the `Controller/Keyboard/Whitefox.bash` file to point to the aria layout `BaseMap="scancode_map scancode_map.aria"` this was originally the scancode_map.truefox

5. After building the keyboard the p key doesn't work, the backspace and / character are switched and a few other issues are coming up.

The LED's also don't work.

I've tried entering the debugging the matrix key by key and updating the scancode_map.aria file but unfortunately I get the same result.

**Comment by haata** [comment]
I believe this is fixed.

Please use the `Keyboards/whitefox.aria.bash` to build. Re-open if still broken.
