### ISSUE TITLE
Whitefox Aria - LEDs do not work

### ISSUE THREAD

**Issue by JBonifacio** [kiibohd/controller#227]
When building the .bin file with the new pixel changes, flashing the file results in a functional keyboard but the LEDs don't seem to work.

I believe by default they should be on.  They never turn on.  I've also mapped the increased LED brightness, decrease LED brightness, and toggle LEDs.  All three of those keys are unresponsive and do not change the status of the LEDs.

**Comment by rammoo** [comment]
I'm also experiencing this on a WhiteFox TrueFox

**Comment by haata** [comment]
Confirmed, working on a fix.

**Comment by JBonifacio** [comment]
Commit [799fc1d](https://github.com/kiibohd/controller/commit/799fc1d980f6c87e0e34c6fbf588aa85cf607887) has resolved this issue.  The capability ledControl() has changed though, and mode 0 and 1 now increase/decrease the brightness and mode 5 toggles the LEDS on and off.  

I am running into some random problems were toggling to disable, then toggling to re-enable all LEDs will only toggle the LED for the down key arrow.  Plugging and unplugging resolves this though.

**Comment by haata** [comment]
@JBonifacio can you provide some KLL options and some instructions to reproduce?

(I haven't finished working on this fix yet, there are some Infinity Ergodox and Infinity 60% issues I'm still working through).

**Comment by JBonifacio** [comment]
I put the two layers I was trying to use in the zipped file.  I'll continue using it as is to see if I can reproduce the ledcontrol issues.

[Archive.zip](https://github.com/kiibohd/controller/files/1476267/Archive.zip)

**Comment by haata** [comment]
I'm going to mark this as fixed, @JBonifacio please open a new issue if you can get a repro case.

Some additional fixes when in here: https://github.com/kiibohd/controller/commit/1b55be17f1894c82e000d28518e8d9dff34462f4
