### ISSUE TITLE
Ergodox Intermittent Drops 

### ISSUE THREAD

**Issue by jbondeson** [kiibohd/controller#228]
The Ergodox is experiencing an intermittent drop across the interconnect. Occasionally the slave will become unresponsive (master is still working) until the slave is disconnected and reconnected.

**Comment by haata** [comment]
Is this still occurring?

**Comment by dfaught** [comment]
I experienced the symptoms described by @jbondeson this morning, approximately an hour after pulling the latest, building and flashing.  Disconnecting and reconnecting restored the slave.

**Comment by dfaught** [comment]
Still experiencing this along with the stuck keys issues.

**Comment by haata** [comment]
I believe this is now fixed, please pull from the latest configurator (or rebase and manually compile).
