### ISSUE TITLE
mouseOut does not take negative values 

### ISSUE THREAD

**Issue by LechnerMartin** [kiibohd/controller#233]
Hi, 
I encountered an issue with the mouseOut command.
It seems that negative values (as shown in mouseTest.kll)
are no longer allowed: 

U"Up" : mouseOut( 0, 0, 1 );  => works
U"Down" : mouseOut( 0, 0, **-1** ); => error

ERROR: OperationSpecificsStage:parse -> /tmp/kll/kll_layouts@['mouseTest']_processed.kll:37
[Token('USBCode', 'U"A"'), Token('Operator', ':'), Token('Name', 'mouseOut'), Token('Parenthesis', '('), Token('Number', '0'), Token('Comma', ','), Token('Dash', '-'), Token('Number', '5'), Token('Comma', ','), Token('Number', '0'), Token('Parenthesis', ')')]
**got unexpected token: 1,15-1,15: Dash '-'**

How can I get the mouse to move in the other direction?

And another question: 
The mouse moves pretty fast, but fraction values seems not to be supported.
LexerError cannot tokenize data: 1,16: " mouseOut( 0, 0.5, 0 )"
How can I fix this?

BestRegards and thanks for the great work!
Martin

**Comment by haata** [comment]
I believe this has been fixed with https://github.com/kiibohd/kll/commit/cece0166d99b4ade3a5bbd319113933b706886fe
