### ISSUE TITLE
K-Type Menu key not working

### ISSUE THREAD

**Issue by skuko** [kiibohd/controller#234]
as the subject says, menu button is not functional. the LED is lit, but the button does not actually do anything. 

verified but multiple people (in massdrop discussion). tested with different switches to eliminate the possibility of a defect switch.

also persists after flashing the "no animation" firmware.

**Comment by JasonIRL** [comment]
@skuko I was able to resolve the issue by changing it from "menu" to "app" in the configurator. Does that work for you?

**Comment by skuko** [comment]
Yeah, that worked for me too, cheers

**Comment by haata** [comment]
The default K-Type layout now uses "app".

https://github.com/kiibohd/controller/commit/630594a537c5d740557fb8ded93bfcf901ee249f

Configurator has also made this switch.
