### ISSUE TITLE
cli.c.o Operator && has no right operand

### ISSUE THREAD

**Issue by LaikeSF** [kiibohd/controller#267]
* **Device**:
Ergodox Infinity

* **Firmware Origin**:
git.repo

* **OS**:
Windows 10 Bash

I have been trying to compile using Windows 10 bash shell. I am getting the following error when I try to compile any firmware, both using the stock layout or my own.

* **Resulting Issue**:
[  2%] Building C object CMakeFiles/kiibohd.dir/Debug/cli/cli.c.o
../../Debug/cli/cli.c: In function 'cliFunc_version':
../../Debug/cli/cli.c:714:47: error: operator '&&' has no right operand
 #if CLI_RevisionNumber && CLI_VersionRevNumber
                                               ^
make[2]: *** [CMakeFiles/kiibohd.dir/Debug/cli/cli.c.o] Error 1
make[1]: *** [CMakeFiles/kiibohd.dir/all] Error 2
make: *** [all] Error 2
Error in build. Exiting..

**Comment by haata** [comment]
Have pulled the latest sources from git? (An issue like this was fixed
recently).

**Comment by LaikeSF** [comment]
I've tried this across two different builds over the last several days. I pulled the latest source just before I copied the error this morning.

**Comment by isabelacmor** [comment]
I'm also seeing this using the latest version of the repo on MacOS. This is even when running the standard `./whitefox.truefox.bash` without any of my custom klls.

**Comment by haata** [comment]
@isabelacmor do you use MacPorts or Brew?

**Comment by isabelacmor** [comment]
@haata I'm using Brew.

**Comment by haata** [comment]
Cool, that's what I'm using as well. Let me test out a fresh clone.

**Comment by haata** [comment]
I've verified the fix on my own macOS box with Brew.

This would happen on github forks without any tags set (git computations get confused).
Let me know if there are any more issues.

**Comment by isabelacmor** [comment]
Confirming that this fix works when cloning the repo, but not when running in a downloaded and unzipped copy.

Thanks for the fix!
