### ISSUE TITLE
OSX entering password while FileVault is enabled does not work

### ISSUE THREAD

**Issue by kkoltzau** [kiibohd/controller#273]
Keyboard does not work when on the bootup password prompt while FileVault is enabled.
Everything works fine once you get past the password prompt.

Using git bisect, the issue was introduced with commit 3b89b8a26efe47fe2a7a807741f726f79b235a6e

* **Device**:
K-Type (Massdrop November 2017)

* **Firmware Origin**:
controller.git repo

* **OS**:
macOS High Sierra 10.13.3

**Comment by kkoltzau** [comment]
I believe I found the cause, please see #274

**Comment by haata** [comment]
Yay!
Thanks a bunch. Let me know if there are still issues.
