### ISSUE TITLE
LCD not restored after key press following Latch

### ISSUE THREAD

**Issue by dfaught** [kiibohd/controller#295]
* **Device**:
Infinity Ergodox Right-side Master (Massdrop 2017)

* **Firmware Origin**:
latest pull from git

* **OS**:
Arch Linux 4.18.8

* **Reproduction Steps**:
Local compile and flash of latest firmware.  Both sides flashed.

* **Resulting Issue**:
After flashing firmware from the latest pull Latch# keys no longer restore the LCD to proper state after next key.

**Comment by dfaught** [comment]
Ping.

This is still an issue.  In fact, it's worse. Slave side is non-operational using the latest build.  Flashed both sides independently, whichever side is the slave is non-responsive.

**Comment by haata** [comment]
kk, I shall take a look.

**Comment by dfaught** [comment]
Stepping back through commits, 449d4d9cd5097f129b0ee9b565cab656f8ae282f is the last commit I found where the slave half functions.  LCD behavior is consistent with the original bug.

**Comment by dfaught** [comment]
Bump... still an issue building against HEAD

**Comment by haata** [comment]
I'm noticing a few issues on Infinity Ergodox with the LCD status.
Right now I'm using the lcdFuncMap.kll to handle the state transitions. One possible fix is to move to the internal layer signals. The downside of doing this is that KLL configurations will need to be updated (possible re-written) to work with the configurator (it's the right thing to do though).

**Comment by dfaught** [comment]
I'm happy to re-write my klls if it will resolve the issue.  I'll also try to get a debug capture of the layer stack tomorrow once I get in to the office.  Debugging my keyboard beats my real job...

**Comment by haata** [comment]
I haven't gone through a full set of testing, but this should fix the LCD update issues.

There may still be bugs but these will be more to do with the layer trigger events.

**Comment by dfaught** [comment]
Confirmed.  Built from head this morning.  Flashed both sides.  LCD is properly restored after post latch key press.

**Comment by haata** [comment]
Pushed to the configurator now.
