### ISSUE TITLE
Indicator Fade does not appear to do anything.

### ISSUE THREAD

**Issue by OvahKeel** [kiibohd/controller#318]
* **Device**:
Kira

* **Firmware Origin**:
Github

* **OS**:
Windows 10

* **Version**:
5.4.1

* **Reproduction Steps**:
CTRL+ALT+F5

* **Resulting Issue**:
Iayer indicator fading does not change at all (faster or slower).

**Comment by haata** [comment]
RCtrl+RAlt+F5 controls the fade period of the lock LEDs

**Comment by OvahKeel** [comment]
Looks like the Wiki page was incorrect.
