### ISSUE TITLE
Visual Speed doesn't reset on V:reset

### ISSUE THREAD

**Issue by Zurry** [kiibohd/controller#334]
When increasing/decreasing animation speed, V:Reset does not reset the speed to default.

* **Device**:
Kira

* **Firmware Origin**:
Configurator App

* **OS**:
Windows 10

* **Version**:
Newest as of 2/14

* **Reproduction Steps**:
Set any animation. Change the speed with hotkeys. V:RESET.

* **Resulting Issue**:
Does not reset visual speed to default.

**Comment by haata** [comment]
So, I can't reset the animation speed directly (as animation speed is actually defined by the LED driver hardware itself).
However, what I can do is provide a capability that (when defined as a combo macro) will do the same thing for V:Reset.

At the same time I'm also adding animation speed to the list of settings that work with Save/Load/Defaults.

```
U"Esc" : animation_control(4) + ledControl(9, 0);
# Animations reset + Animation Speed Reset
```

@smasher816 once v0.5.5 is released you'll need to change what V:Reset maps to as I'll be updating `release.1.layer.2.ll`.
