### ISSUE TITLE
V:Clear makes right side of keyboard flicker

### ISSUE THREAD

**Issue by Zurry** [kiibohd/controller#335]
* **Device**:
Kira

* **Firmware Origin**:
Configurator

* **OS**:
Windows 10

* **Version**:
Newest as of 2/15

* **Reproduction Steps**:
Set Custom Wave animation. Set a hotkey to V:CEAR and press it. It makes the right side of the animation flicker. (I'm not sure what this key is supposed to do anyways.)

* **Resulting Issue**:
Right side of keyboard flickers instead of intended action.

**Comment by haata** [comment]
Fixed for v0.5.5
