### ISSUE TITLE
Assign Action: Animation Control > Single does not behave as intended.

### ISSUE THREAD

**Issue by Zurry** [kiibohd/controller#336]
* **Device**:
Kira

* **Firmware Origin**:
Configurator

* **OS**:
Windows 10

* **Version**:
Most recent as of 2/15.

* **Reproduction Steps**:
Set a Custom wave.
Create Second Custom Wave
Assign a key to Animation > Second Custom Wave > Single

* **Resulting Issue**:
Animation starts statically, does not animate. Does not switch back to original animation.

**Comment by haata** [comment]
Should be fixed with v0.5.5.
