### ISSUE TITLE
'make' fails with cli.c undefined reference errors (screenshot attached)

### ISSUE THREAD

**Issue by fucema** [kiibohd/controller#34]
Ubuntu 14.10 mini, in a Virtualbox VM x86_64
Linux kernal 3.16.0-33-generic

I've followed build documentation here but am failing with several errors related to cli.c. Any help provided is appreciated!

![2015-04-08 00_33_03-ubuntu 14 10 mini running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/19499/7039069/da9ba046-dd89-11e4-90d4-d4f2d82a841a.png)

**Comment by haata** [comment]
Interesting. There were some recent code changes in the cli, I'll give it a check.

**Comment by haata** [comment]
Just pushed a change. Sorry about that, haven't compiled from master in a few days.

**Comment by fucema** [comment]
Yeaaaaaaaa baby, thanks for the fix! I was going mad trying to figure out what I was doing wrong.
