### ISSUE TITLE
K Type configuration doesn't transfer over keyboard

### ISSUE THREAD

**Issue by Aklipses** [kiibohd/controller#345]
Back in December 2017 - January 2018, I was able to change the configurations of my keyboard such as key map and LED animation.  Now 2019, I had downloaded the new configurator for the keyboard.  Any changes in the configurator does not reflect back to the keyboard.

* **Device**:
 K-Type (Massdrop December 2017)

* **Firmware Origin**:
 Unsure

* **OS**:
 Windows 10 Pro 64 Bit

* **Version**:
Windows: libusbK (v3.0.7.0)?

* **Reproduction Steps**:
1. Flash mode keyboard
2. Change key map or led animations.
3. Flash keyboard successful.
4. Changes in configuration does not reflect back to the keyboard.

* **Resulting Issue**:
 After flashing sucessfully, configurations does not transfer into the keyboard whether is it key mapping or led animation.

**Comment by haata** [comment]
The previous firmware has a bug where the brightness of the keyboard always defaults to 0. This will be fixed in the new firmware.
I'll have a beta out for v0.5.5 in the next day or so.
