### ISSUE TITLE
USB port disabled on K-Type after customization of firmware

### ISSUE THREAD

**Issue by timesscar** [kiibohd/controller#346]
I'm having an issue where if I create a new firmware with more color animations, and reflash my board, the right USB port stops working.  If I put the board into reflash mode the port starts working for that purpose again.  If I reflash the board back to the stock firmware, everything works normally too.

* **Device**:
 * K-Type (Massdrop November 2017)

* **Firmware Origin**:
Kiibohd configurator

* **OS**:
Windows 10 Version 1809

* **Version**:

* **Reproduction Steps**:
Use the configurator to create any animation (in this case I used the Miami wave built in pattern).  reflash the device.  The USB port is disabled.  Reflash the device with the default firmware (The one marked Standard in the UI) and the port is restored.

* **Resulting Issue**:
USB port is disabled for normal use (works for reflashing)

**Comment by timesscar** [comment]
Here is the json as requested

[kiibohd-json.txt](https://github.com/kiibohd/controller/files/2916281/kiibohd-json.txt)

**Comment by timesscar** [comment]
An update, I went through a testing cycle again, and I was incorrect above, the stock firmware from the kiibohd configurator does not fix the problem.  However, the one from the online configurator does.

**Comment by haata** [comment]
Confirmed not working, still investigating a fix for this.

**Comment by haata** [comment]
Fixed, will be in v0.5.5

**Comment by haata** [comment]
If you'd like to verify, you can try the beta: https://github.com/kiibohd/controller/releases/tag/v0.5.5-beta

Download the K-Type bin file and use QuickFlash to load the firmware.
https://kiibohd.github.io/wiki/#/Configurator/Quickflash
