### ISSUE TITLE
Ergodox Infinity Only one hand works at a time

### ISSUE THREAD

**Issue by cogliostro** [kiibohd/controller#349]
Device: Ergodox
Firmware Origin:Kiibohd configurator
OS: Fedora
Version: 29

Reproduction Steps:
Flash each hand with either firmware from configurator or compiled from controller repo.

Resulting Issue:
Only the device directly connected to the computer works. Both work if i connect them independently to the computer.

**Comment by haata** [comment]
I'll take a look at this. I thought this was working.

This was working before? You haven't changed the interconnect cable?

**Comment by cogliostro** [comment]
Same cable as before. Just new firmware.

**Comment by dfaught** [comment]
I've been experiencing this for a while.  The last working commit I've been able to use for the Ergodox was:  https://github.com/kiibohd/controller/commit/449d4d9cd5097f129b0ee9b565cab656f8ae282f

**Comment by cogliostro** [comment]
Can confirm that commit works for me too.

**Comment by haata** [comment]
Confirmed broken. Also confirmed its an issue with the master (not the slave devices).

**Comment by haata** [comment]
Should be fixed now. Make sure to flash both sides.

**Comment by haata** [comment]
If you'd like to verify, you can try the beta: https://github.com/kiibohd/controller/releases/tag/v0.5.5-beta
