### ISSUE TITLE
SYS/CON codes from KLL doesn't work

### ISSUE THREAD

**Issue by kaansoral** [kiibohd/controller#35]
I hope I'm missing something obvious but the SYS/CON definitions doesn't work

U"P" : CON”Play”;

For example

The Consumer/System code table is impressive, can't wait to try them, yet couldn't figure out how to do it yet

**Comment by kaansoral** [comment]
sysCtrlOut / consCtrlOut / usbKeyOut functions should be used instead, for those who stumble onto this issue

so far I'm loving the firmware, it requires a bit digging, but it's been rewarding so far

**Comment by haata** [comment]
Apologies on the CON"Play" part. I just finished that part of the spec last weekend. Haven't finished the compiler part (almost there though :D). I'll update this once it's working.

Thanks a lot for the bug reports.

**Comment by kaansoral** [comment]
No problem, it was a joy to use the firmware, once the bugs are solved, it will probably flourish

One small bug that I noticed is: changing the defaultMap name on the .bash file doesn't work, the Scan/MD1 one is used instead (I added my custom .kll's to the kll/layouts folder, only the default one isn't recognized)

**Comment by haata** [comment]
I've just pushed the update to the kll compiler. Make sure you update the kll directory git repo.
Let me know if you have any issues.
