### ISSUE TITLE
MD2?

### ISSUE THREAD

**Issue by unphased** [kiibohd/controller#52]
My Infinity keyboard wasn't the first massdrop group buy, I got mine with the last one that had the bent plate. 

What's MD2? Is it for the fancy new ergodox with the screen on it?

Anyways, I tried building with `ScanModule=MD2` and I ended up with a strange compile error: 

```
Linking C executable kiibohd.elf
/usr/local/Cellar/cmake/3.0.0/bin/cmake -E cmake_link_script CMakeFiles/kiibohd.elf.dir/link.txt --verbose=1
/usr/local/bin/arm-none-eabi-gcc    -Wl,-headerpad_max_install_names   -mthumb -nostdlib -fdata-sections -ffunction-sections -fshort-wchar -fno-builtin -nostartfiles -Wl,-Map=link.map,--cref -Wl,--gc-sections -Wl,--no-wchar-size-warning -T/Users/steven/Documents/kiibohd-controller/Lib/mk20dx128vlf5.ld CMakeFiles/kiibohd.elf.dir/main.c.o CMakeFiles/kiibohd.elf.dir/Lib/mk20dx.c.o CMakeFiles/kiibohd.elf.dir/Lib/delay.c.o CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o CMakeFiles/kiibohd.elf.dir/Scan/MatrixARM/matrix_scan.c.o CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o CMakeFiles/kiibohd.elf.dir/Macro/PartialMap/macro.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/output_com.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_desc.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_dev.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_keyboard.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_mem.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_serial.c.o CMakeFiles/kiibohd.elf.dir/Debug/cli/cli.c.o CMakeFiles/kiibohd.elf.dir/Debug/led/led.c.o CMakeFiles/kiibohd.elf.dir/Debug/print/print.c.o  -o kiibohd.elf
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_BufferLen':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:358: multiple definition of `I2C_BufferLen'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:440: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_BufferPush':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:367: multiple definition of `I2C_BufferPush'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:449: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_TxBufferPop':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:394: multiple definition of `I2C_TxBufferPop'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:476: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `i2c0_isr':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:119: multiple definition of `i2c0_isr'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:136: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_Send':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:444: multiple definition of `I2C_Send'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:526: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `cliFunc_i2cRecv':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:630: multiple definition of `cliFunc_i2cRecv'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:648: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `cliFunc_i2cSend':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:582: multiple definition of `cliFunc_i2cSend'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:600: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `LED_zeroPages':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:243: multiple definition of `LED_zeroPages'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:281: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `cliFunc_ledZero':
/Users/steven/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:678: multiple definition of `cliFunc_ledZero'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/steven/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:702: first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.data.I2C_RxBuffer+0x0): multiple definition of `I2C_RxBuffer'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.data.I2C_RxBuffer+0x0): first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.data.I2C_TxBuffer+0x0): multiple definition of `I2C_TxBuffer'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.data.I2C_TxBuffer+0x0): first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.rodata.ledZeroCLIDict_DescEntry+0x0): multiple definition of `ledZeroCLIDict_DescEntry'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.rodata.ledZeroCLIDict_DescEntry+0x0): first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.rodata.i2cSendCLIDict_DescEntry+0x0): multiple definition of `i2cSendCLIDict_DescEntry'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.rodata.i2cSendCLIDict_DescEntry+0x0): first defined here
CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.rodata.i2cRecvCLIDict_DescEntry+0x0): multiple definition of `i2cRecvCLIDict_DescEntry'
CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.rodata.i2cRecvCLIDict_DescEntry+0x0): first defined here
/usr/local/Cellar/gcc-arm-none-eabi/20130916/bin/../lib/gcc/arm-none-eabi/4.7.4/../../../../arm-none-eabi/bin/ld: Warning: size of symbol `i2cRecvCLIDict_DescEntry' changed from 121 in CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o to 118 in CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o
collect2: error: ld returned 1 exit status
make[2]: *** [kiibohd.elf] Error 1
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
make: *** [all] Error 2

```

I am just hoping that this isn't actually ready yet and I should actually be using MD1. (which I have been until now)

**Comment by haata** [comment]
MD2 is/was supposed to come right after the Infinity keyboard.
Unfortunately, stuff happened and that keyboard was mostly shelved.
The main interesting parts of MD2 became MDErgo1 (Infinity ErgoDox).

I may use MD2 for a future keyboard though.

On Sat, Jun 13, 2015 at 7:37 PM Steven Lu <notifications@github.com> wrote:

> I see various MD2 source. My Infinity keyboard wasn't the first massdrop
> group buy, I got mine with the last one that had the bent plate.
>
> Anyways, I tried building with ScanModule=MD2 and I ended up with a
> strange compile error:
>
> [ 77%] [ 83%] [ 88%] [ 94%] Building C object CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_serial.c.o                                                                                                                                                                                                                                    │······························
> /usr/local/bin/arm-none-eabi-gcc   -I.. -I.    -mcpu=cortex-m4 -DF_CPU=48000000 -D_mk20dx128vlf5_=1 -Os -mthumb -nostdlib -fdata-sections -ffunction-sections -fshort-wchar -fno-builtin -nostartfiles -Wall -ggdb3 -std=gnu11 -MMD -I/Users/lust/Documents/kiibohd-controller/Scan/ISSILed -I/Users/lust/Documents/kiibohd-controller/Scan/Ma│······························
> trixARM -I/Users/lust/Documents/kiibohd-controller/Scan/MD2 -I/Users/lust/Documents/kiibohd-controller/Macro/PartialMap -I/Users/lust/Documents/kiibohd-controller/Output/pjrcUSB -I/Users/lust/Documents/kiibohd-controller/Debug/cli -I/Users/lust/Documents/kiibohd-controller/Debug/led -I/Users/lust/Documents/kiibohd-controller/Debug/p│······························
> rint -I/Users/lust/Documents/kiibohd-controller/Debug/full -o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_serial.c.o   -c ../Output/pjrcUSB/arm/usb_serial.c                                                                                                                                                                            │······························
> Building C object CMakeFiles/kiibohd.elf.dir/Debug/cli/cli.c.o                                                                                                                                                                                                                                                                                │······························
> /usr/local/bin/arm-none-eabi-gcc   -I.. -I.    -mcpu=cortex-m4 -DF_CPU=48000000 -D_mk20dx128vlf5_=1 -Os -mthumb -nostdlib -fdata-sections -ffunction-sections -fshort-wchar -fno-builtin -nostartfiles -Wall -ggdb3 -std=gnu11 -MMD -I/Users/lust/Documents/kiibohd-controller/Scan/ISSILed -I/Users/lust/Documents/kiibohd-controller/Scan/Ma│······························
> trixARM -I/Users/lust/Documents/kiibohd-controller/Scan/MD2 -I/Users/lust/Documents/kiibohd-controller/Macro/PartialMap -I/Users/lust/Documents/kiibohd-controller/Output/pjrcUSB -I/Users/lust/Documents/kiibohd-controller/Debug/cli -I/Users/lust/Documents/kiibohd-controller/Debug/led -I/Users/lust/Documents/kiibohd-controller/Debug/p│······························
> rint -I/Users/lust/Documents/kiibohd-controller/Debug/full -o CMakeFiles/kiibohd.elf.dir/Debug/cli/cli.c.o   -c ../Debug/cli/cli.c                                                                                                                                                                                                            │······························
> Building C object CMakeFiles/kiibohd.elf.dir/Debug/led/led.c.o                                                                                                                                                                                                                                                                                │······························
> Building C object CMakeFiles/kiibohd.elf.dir/Debug/print/print.c.o                                                                                                                                                                                                                                                                            │······························
> /usr/local/bin/arm-none-eabi-gcc   -I.. -I.    -mcpu=cortex-m4 -DF_CPU=48000000 -D_mk20dx128vlf5_=1 -Os -mthumb -nostdlib -fdata-sections -ffunction-sections -fshort-wchar -fno-builtin -nostartfiles -Wall -ggdb3 -std=gnu11 -MMD -I/Users/lust/Documents/kiibohd-controller/Scan/ISSILed -I/Users/lust/Documents/kiibohd-controller/Scan/Ma│······························
> trixARM -I/Users/lust/Documents/kiibohd-controller/Scan/MD2 -I/Users/lust/Documents/kiibohd-controller/Macro/PartialMap -I/Users/lust/Documents/kiibohd-controller/Output/pjrcUSB -I/Users/lust/Documents/kiibohd-controller/Debug/cli -I/Users/lust/Documents/kiibohd-controller/Debug/led -I/Users/lust/Documents/kiibohd-controller/Debug/p│······························
> rint -I/Users/lust/Documents/kiibohd-controller/Debug/full -o CMakeFiles/kiibohd.elf.dir/Debug/print/print.c.o   -c ../Debug/print/print.c                                                                                                                                                                                                    │······························
> /usr/local/bin/arm-none-eabi-gcc   -I.. -I.    -mcpu=cortex-m4 -DF_CPU=48000000 -D_mk20dx128vlf5_=1 -Os -mthumb -nostdlib -fdata-sections -ffunction-sections -fshort-wchar -fno-builtin -nostartfiles -Wall -ggdb3 -std=gnu11 -MMD -I/Users/lust/Documents/kiibohd-controller/Scan/ISSILed -I/Users/lust/Documents/kiibohd-controller/Scan/Ma│······························
> trixARM -I/Users/lust/Documents/kiibohd-controller/Scan/MD2 -I/Users/lust/Documents/kiibohd-controller/Macro/PartialMap -I/Users/lust/Documents/kiibohd-controller/Output/pjrcUSB -I/Users/lust/Documents/kiibohd-controller/Debug/cli -I/Users/lust/Documents/kiibohd-controller/Debug/led -I/Users/lust/Documents/kiibohd-controller/Debug/p│······························
> rint -I/Users/lust/Documents/kiibohd-controller/Debug/full -o CMakeFiles/kiibohd.elf.dir/Debug/led/led.c.o   -c ../Debug/led/led.c                                                                                                                                                                                                            │······························
> Linking C executable kiibohd.elf                                                                                                                                                                                                                                                                                                              │······························
> /usr/local/Cellar/cmake/3.0.0/bin/cmake -E cmake_link_script CMakeFiles/kiibohd.elf.dir/link.txt --verbose=1                                                                                                                                                                                                                                  │······························
> /usr/local/bin/arm-none-eabi-gcc    -Wl,-headerpad_max_install_names   -mthumb -nostdlib -fdata-sections -ffunction-sections -fshort-wchar -fno-builtin -nostartfiles -Wl,-Map=link.map,--cref -Wl,--gc-sections -Wl,--no-wchar-size-warning -T/Users/lust/Documents/kiibohd-controller/Lib/mk20dx128vlf5.ld CMakeFiles/kiibohd.elf.dir/main.c│······························
> .o CMakeFiles/kiibohd.elf.dir/Lib/mk20dx.c.o CMakeFiles/kiibohd.elf.dir/Lib/delay.c.o CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o CMakeFiles/kiibohd.elf.dir/Scan/MatrixARM/matrix_scan.c.o CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o CMakeFiles/kiibohd.elf.dir/Macro/PartialMap/macro.c.o CMakeFiles/kiibohd.elf.dir/Output│······························
> /pjrcUSB/output_com.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_desc.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_dev.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_keyboard.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_mem.c.o CMakeFiles/kiibohd.elf.dir/Output/pjrcUSB/arm/usb_serial.c.o CMakeFiles/│······························
> kiibohd.elf.dir/Debug/cli/cli.c.o CMakeFiles/kiibohd.elf.dir/Debug/led/led.c.o CMakeFiles/kiibohd.elf.dir/Debug/print/print.c.o  -o kiibohd.elf                                                                                                                                                                                               │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_BufferLen':                                                                                                                                                                                                                                                               │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:358: multiple definition of `I2C_BufferLen'                                                                                                                                                                                                                            │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:440: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_BufferPush':                                                                                                                                                                                                                                                              │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:367: multiple definition of `I2C_BufferPush'                                                                                                                                                                                                                           │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:449: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_TxBufferPop':                                                                                                                                                                                                                                                             │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:394: multiple definition of `I2C_TxBufferPop'                                                                                                                                                                                                                          │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:476: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `i2c0_isr':                                                                                                                                                                                                                                                                    │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:119: multiple definition of `i2c0_isr'                                                                                                                                                                                                                                 │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:136: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `I2C_Send':                                                                                                                                                                                                                                                                    │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:444: multiple definition of `I2C_Send'                                                                                                                                                                                                                                 │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:526: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `cliFunc_i2cRecv':                                                                                                                                                                                                                                                             │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:630: multiple definition of `cliFunc_i2cRecv'                                                                                                                                                                                                                          │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:648: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `cliFunc_i2cSend':                                                                                                                                                                                                                                                             │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:582: multiple definition of `cliFunc_i2cSend'                                                                                                                                                                                                                          │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:600: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `LED_zeroPages':                                                                                                                                                                                                                                                               │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:243: multiple definition of `LED_zeroPages'                                                                                                                                                                                                                            │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:281: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o: In function `cliFunc_ledZero':                                                                                                                                                                                                                                                             │······························
> /Users/lust/Documents/kiibohd-controller/build/../Scan/MD2/scan_loop.c:678: multiple definition of `cliFunc_ledZero'                                                                                                                                                                                                                          │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:/Users/lust/Documents/kiibohd-controller/build/../Scan/ISSILed/led_scan.c:702: first defined here                                                                                                                                                                                        │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.data.I2C_RxBuffer+0x0): multiple definition of `I2C_RxBuffer'                                                                                                                                                                                                                             │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.data.I2C_RxBuffer+0x0): first defined here                                                                                                                                                                                                                                             │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.data.I2C_TxBuffer+0x0): multiple definition of `I2C_TxBuffer'                                                                                                                                                                                                                             │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.data.I2C_TxBuffer+0x0): first defined here                                                                                                                                                                                                                                             │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.rodata.ledZeroCLIDict_DescEntry+0x0): multiple definition of `ledZeroCLIDict_DescEntry'                                                                                                                                                                                                   │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.rodata.ledZeroCLIDict_DescEntry+0x0): first defined here                                                                                                                                                                                                                               │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.rodata.i2cSendCLIDict_DescEntry+0x0): multiple definition of `i2cSendCLIDict_DescEntry'                                                                                                                                                                                                   │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.rodata.i2cSendCLIDict_DescEntry+0x0): first defined here                                                                                                                                                                                                                               │······························
> CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o:(.rodata.i2cRecvCLIDict_DescEntry+0x0): multiple definition of `i2cRecvCLIDict_DescEntry'                                                                                                                                                                                                   │······························
> CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o:(.rodata.i2cRecvCLIDict_DescEntry+0x0): first defined here                                                                                                                                                                                                                               │······························
> /usr/local/Cellar/gcc-arm-none-eabi/20130916/bin/../lib/gcc/arm-none-eabi/4.7.4/../../../../arm-none-eabi/bin/ld: Warning: size of symbol `i2cRecvCLIDict_DescEntry' changed from 121 in CMakeFiles/kiibohd.elf.dir/Scan/ISSILed/led_scan.c.o to 118 in CMakeFiles/kiibohd.elf.dir/Scan/MD2/scan_loop.c.o                                     │······························
> collect2: error: ld returned 1 exit status                                                                                                                                                                                                                                                                                                    │······························
> make[2]: *** [kiibohd.elf] Error 1                                                                                                                                                                                                                                                                                                            │······························
> make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2                                                                                                                                                                                                                                                                                         │······························
> make: *** [all] Error 2
>
> I am just hoping that this isn't actually ready yet and I should actually
> be using MD1. (which I have been until now)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kiibohd/controller/issues/52>.
>

**Comment by kaansoral** [comment]
Wow, very curious :)

How was MD2 like?
