### ISSUE TITLE
NKRO/Boot mode capabilities not working on teensy 3.1?

### ISSUE THREAD

**Issue by schizoidpig** [kiibohd/controller#58]
So I wired a keyboard with a teensy 3.1, and everything worked exactly as I wanted to, except I could not use my keyboard in my grub bootloader when I start up my computer. So I configured f9 and f10 to set NKRO and Boot respectively in my function layer. However, this seems to have no effect and I still cannot use my keyboard in grub. Also I used this link https://www.microsoft.com/appliedsciences/content/projects/KeyboardGhostingDemo.aspx to verify that my keyboard is always in NKRO mode.

Here is the code in my kll file, accessed via layerShift ( 1 );
U"F9" : kbdProtocolNKRO();
U"F10" : kbdProtocolBoot();

I'm using arch linux 64bit.

**Comment by dumle29** [comment]
If you connect to the keyboard using a serial monitor (On the MD1 you have to jumper the two center header pins, I don't know if it's different on the other versions)

hit enter, then type help and hit enter.
You should get a list of commands. Run kbdProtocol. 1 = NKRO 0 = BIOS

**Comment by schizoidpig** [comment]
Okay I used "screen /dev/ttyACM0" in my terminal to connect to the keyboard. kbdProtocol returns 1.

**Comment by dumle29** [comment]
What OS are you running?

**Comment by schizoidpig** [comment]
Arch linux 64bit

**Comment by dumle29** [comment]
what does the command return if you set it to BIOS mode?

**Comment by schizoidpig** [comment]
Well, after using fn +f10, which is set to kbdProtocolBoot(), there is no change.

**Comment by dumle29** [comment]
odd

**Comment by Streetwalrus** [comment]
I can confirm this issue on the same setup, using a Teensy 3.1 and the keyboard always reports being in NKRO mode even if I map a key to switch to boot mode and press it. Keyboard doesn't work in the BIOS/bootloader as a result.

**Comment by haata** [comment]
I shall look at this in the next couple of days.

**Comment by Streetwalrus** [comment]
I've just tried again, connecting the keyboard directly to the PC without a hub allows me to use it in the UEFI menu and in rEFInd, probably because my UEFI has extended HID support (you can use the mouse to browse the menu). That said the keyboard is still stuck in NKRO mode and I can't "hold DEL to enter setup", though that might be due to the firmware taking a little while to init.

**Comment by haata** [comment]
This should working now after a bunch of USB fixes in the past few months.
