### ISSUE TITLE
Failing build due to missing usb_joystick.c and usb_mouse.c

### ISSUE THREAD

**Issue by bburky** [kiibohd/controller#59]
`arm/usb_joystick.c` and `arm/usb_mouse.c` were just introduced by 20b62afb9a05a64b1f15c6329866600913775eea in [Output/pjrcUSB/setup.cmake](https://github.com/kiibohd/controller/blob/20b62afb9a05a64b1f15c6329866600913775eea/Output/pjrcUSB/setup.cmake#L29). These files have not been committed so the cmake build (via `infinity.bash`) fails.

It looks like these includes were accidentally introduced with work on #4.

Simply commenting out the lines allows the build to succeed.

**Comment by haata** [comment]
Oops, they should be included.

1cbc1755514bb2a012c7b045fc29d20dd3563e77

Thanks for reporting this

**Comment by bburky** [comment]
Great, works fine now.
