### ISSUE TITLE
Unnecessary scrollbars added to windows in OS X Yosemite

### ISSUE THREAD

**Issue by dalkire** [kiibohd/controller#60]
When using the Infinity keyboard, the firmware will add unnecessary scrollbars to textEdit and iTerm2 windows for example. When I press the button to flash the firmware, the scrollbars disappear, but as soon as the firmware is loaded, they show up again. Possibly related to joystick and mouse descriptors.

**Comment by johnhamelink** [comment]
This happens in El Capitan also.

**Comment by haata** [comment]
I'm going to try to see if I can reproduce this, haven't been super successful so far...

**Comment by tmk** [comment]
I guess the keyboard has mouse function? If so this will help.

https://github.com/tmk/tmk_keyboard/issues/74

**Comment by haata** [comment]
Thanks hasu!

**Comment by haata** [comment]
Should be resolved now.
