### ISSUE TITLE
KLL Layout error during build

### ISSUE THREAD

**Issue by adamsaj** [kiibohd/controller#62]
I'm trying to build for the Infinity ErgoDox according to the "How To Load Layouts to Keyboard" wiki page, and I'm getting the following error message using the ergodox.bash script:

`funcparserlib.lexer.LexerError: cannot tokenize data: 88,16: "U"PERIOD" : U"V";"`

It displays this message for whatever trigger:response pair is on the bottom of my layout file.

**Comment by haata** [comment]
Hmm, seems to be working on my end. Try making sure you haven't forgotten a semicolon.

If you still have an issue, please attach the entire kll file here.
Thanks.

**Comment by adamsaj** [comment]
I've put the kll files on github at adamsaj/keyboard_layouts. 

The only other thing I've changed is adding the layouts to the build script:
```
# This is the default layer of the keyboard
# NOTE: To combine kll files into a single layout, separate them by spaces
# e.g.  DefaultMap="mylayout mylayoutmod"
DefaultMap="mdergo_base lcdFuncMap"

# This is where you set the additional layers
# NOTE: Indexing starts at 1
# NOTE: Each new layer is another array entry
# e.g.  PartialMaps[1]="layer1 layer1mod"
#       PartialMaps[2]="layer2"
#       PartialMaps[3]="layer3"
PartialMaps[1]="mdergo_numpad"
PartialMaps[2]="mdergo_arrows"
PartialMaps[3]="mdergo_qwerty"
PartialMaps[4]="mdergo_boot"
```

**Comment by haata** [comment]
See my pull request https://github.com/adamsaj/keyboard_layouts/pull/3

**Comment by adamsaj** [comment]
Yikes, I thought I had a better handle on the syntax. Thanks for your help.
