### ISSUE TITLE
Your pin 7 is misslabeled

### ISSUE THREAD

**Issue by Mechanicalanimator** [kiibohd/controller#86]
You have it as B1, but it is D2.

**Comment by haata** [comment]
Which file? Which project? What microcontroller?

**Comment by Mechanicalanimator** [comment]
Sorry, here:
https://github.com/kiibohd/controller/wiki/Custom-Keyboard-using-a-Teensy-3.0-3.1-3.2

The teensy pin

**Comment by haata** [comment]
Thanks! Fixed.

The wiki is public editable iirc.
